%bcond_without tests
%bcond_without weak_deps

%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%global __provides_exclude_from ^/opt/ros/kilted/.*$
%global __requires_exclude_from ^/opt/ros/kilted/.*$

Name:           ros-kilted-rosbag2rawlog
Version:        3.5.0
Release:        1%{?dist}%{?release_suffix}
Summary:        ROS rosbag2rawlog package

License:        BSD
URL:            https://github.com/mrpt/mrpt_ros_bridge
Source0:        %{name}-%{version}.tar.gz

Requires:       cli11-devel
Requires:       ros-kilted-ament-cmake-lint-cmake
Requires:       ros-kilted-ament-cmake-xmllint
Requires:       ros-kilted-ament-lint-auto
Requires:       ros-kilted-cv-bridge
Requires:       ros-kilted-mrpt-libmaps
Requires:       ros-kilted-mrpt-libros-bridge
Requires:       ros-kilted-mrpt-msgs
Requires:       ros-kilted-nav-msgs
Requires:       ros-kilted-rosbag2-cpp
Requires:       ros-kilted-sensor-msgs
Requires:       ros-kilted-tf2-geometry-msgs
Requires:       ros-kilted-tf2-msgs
Requires:       ros-kilted-tf2-ros
Requires:       ros-kilted-ros-workspace
BuildRequires:  cli11-devel
BuildRequires:  cmake3
BuildRequires:  ros-kilted-ament-cmake
BuildRequires:  ros-kilted-ament-cmake-lint-cmake
BuildRequires:  ros-kilted-ament-cmake-xmllint
BuildRequires:  ros-kilted-ament-lint-auto
BuildRequires:  ros-kilted-cv-bridge
BuildRequires:  ros-kilted-mrpt-libmaps
BuildRequires:  ros-kilted-mrpt-libros-bridge
BuildRequires:  ros-kilted-mrpt-msgs
BuildRequires:  ros-kilted-nav-msgs
BuildRequires:  ros-kilted-rosbag2-cpp
BuildRequires:  ros-kilted-sensor-msgs
BuildRequires:  ros-kilted-tf2-geometry-msgs
BuildRequires:  ros-kilted-tf2-msgs
BuildRequires:  ros-kilted-tf2-ros
BuildRequires:  ros-kilted-ros-workspace
Provides:       %{name}-devel = %{version}-%{release}
Provides:       %{name}-doc = %{version}-%{release}
Provides:       %{name}-runtime = %{version}-%{release}

%description
CLI tool to transform between rosbags and rawlogs.

%prep
%autosetup -p1

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kilted/setup.sh" ]; then . "/opt/ros/kilted/setup.sh"; fi
mkdir -p .obj-%{_target_platform} && cd .obj-%{_target_platform}
%cmake3 \
    -UINCLUDE_INSTALL_DIR \
    -ULIB_INSTALL_DIR \
    -USYSCONF_INSTALL_DIR \
    -USHARE_INSTALL_PREFIX \
    -ULIB_SUFFIX \
    -DCMAKE_INSTALL_PREFIX="/opt/ros/kilted" \
    -DAMENT_PREFIX_PATH="/opt/ros/kilted" \
    -DCMAKE_PREFIX_PATH="/opt/ros/kilted" \
    -DSETUPTOOLS_DEB_LAYOUT=OFF \
%if !0%{?with_tests}
    -DBUILD_TESTING=OFF \
%endif
    ..

%make_build

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kilted/setup.sh" ]; then . "/opt/ros/kilted/setup.sh"; fi
%make_install -C .obj-%{_target_platform}

%if 0%{?with_tests}
%check
# Look for a Makefile target with a name indicating that it runs tests
TEST_TARGET=$(%__make -qp -C .obj-%{_target_platform} | sed "s/^\(test\|check\):.*/\\1/;t f;d;:f;q0")
if [ -n "$TEST_TARGET" ]; then
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kilted/setup.sh" ]; then . "/opt/ros/kilted/setup.sh"; fi
CTEST_OUTPUT_ON_FAILURE=1 \
    %make_build -C .obj-%{_target_platform} $TEST_TARGET || echo "RPM TESTS FAILED"
else echo "RPM TESTS SKIPPED"; fi
%endif

%files
/opt/ros/kilted

%changelog
* Tue Feb 17 2026 Markus Bader <markus.bader@tuwien.ac.at> - 3.5.0-1
- Autogenerated by Bloom

* Sat Feb 14 2026 Markus Bader <markus.bader@tuwien.ac.at> - 3.4.0-1
- Autogenerated by Bloom

* Wed Feb 11 2026 Markus Bader <markus.bader@tuwien.ac.at> - 3.3.0-1
- Autogenerated by Bloom

* Fri Feb 06 2026 Markus Bader <markus.bader@tuwien.ac.at> - 3.2.0-1
- Autogenerated by Bloom

* Fri Dec 26 2025 Markus Bader <markus.bader@tuwien.ac.at> - 3.1.1-1
- Autogenerated by Bloom

* Tue Dec 23 2025 Markus Bader <markus.bader@tuwien.ac.at> - 3.1.0-1
- Autogenerated by Bloom

* Sat Nov 08 2025 Markus Bader <markus.bader@tuwien.ac.at> - 3.0.2-1
- Autogenerated by Bloom

* Fri Nov 07 2025 Markus Bader <markus.bader@tuwien.ac.at> - 3.0.1-1
- Autogenerated by Bloom

* Fri Nov 07 2025 Markus Bader <markus.bader@tuwien.ac.at> - 3.0.0-1
- Autogenerated by Bloom

